# Generated by Django 5.1.3 on 2025-11-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('fatigue', 'Fatiga'), ('health', 'Salud'), ('productivity', 'Productividad'), ('safety', 'Seguridad')], db_index=True, max_length=20, verbose_name='Tipo de Alerta')),
                ('level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], db_index=True, max_length=20, verbose_name='Nivel')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
