# Generated by Django 5.1.3 on 2025-11-05 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='metrics.metric', verbose_name='Métrica Relacionada'),
        ),
    ]
