# Generated by Django 5.1.3 on 2025-11-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Marca de Tiempo')),
                ('heart_rate', models.IntegerField(blank=True, help_text='Latidos por minuto', null=True, verbose_name='Frecuencia Cardíaca (bpm)')),
                ('hrv', models.IntegerField(blank=True, help_text='Variabilidad de la frecuencia cardíaca en ms', null=True, verbose_name='Variabilidad de FC (RMSSD)')),
                ('spo2', models.DecimalField(blank=True, decimal_places=2, help_text='Saturación de oxígeno en sangre (%)', max_digits=5, null=True, verbose_name='Nivel de Oxígeno (SpO2)')),
                ('steps', models.IntegerField(default=0, verbose_name='Pasos')),
                ('activity_level', models.IntegerField(blank=True, help_text='0-100: nivel de actividad física', null=True, verbose_name='Nivel de Actividad')),
                ('movement', models.DecimalField(blank=True, decimal_places=2, help_text='Nivel de movimiento general', max_digits=5, null=True, verbose_name='Movimiento')),
                ('stress_level', models.IntegerField(blank=True, help_text='0-100: nivel de estrés detectado', null=True, verbose_name='Nivel de Estrés')),
                ('fatigue_level', models.IntegerField(blank=True, help_text='0-100: nivel de fatiga', null=True, verbose_name='Nivel de Fatiga')),
                ('recovery_score', models.IntegerField(blank=True, help_text='0-100: capacidad de recuperación', null=True, verbose_name='Puntuación de Recuperación')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['-date', '-timestamp'],
            },
        ),
    ]
