# Generated by Django 5.1.3 on 2025-11-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor numérico de la métrica', max_digits=10, verbose_name='Valor')),
                ('stress_category', models.CharField(blank=True, choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], help_text='Categoría de estrés (solo para stress_level)', max_length=10, null=True, verbose_name='Categoría de Estrés')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Marca de Tiempo')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('code', models.CharField(help_text='Código único: heart_rate, steps, stress_level, etc.', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre legible: Frecuencia Cardíaca, Pasos, etc.', max_length=100, verbose_name='Nombre')),
                ('unit', models.CharField(help_text='Unidad por defecto: bpm, pasos, %, ms', max_length=20, verbose_name='Unidad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo permitido', max_digits=10, null=True, verbose_name='Valor Mínimo')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo permitido', max_digits=10, null=True, verbose_name='Valor Máximo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Métrica',
                'verbose_name_plural': 'Tipos de Métricas',
                'ordering': ['name'],
            },
        ),
    ]
