# Generated by Django 5.1.3 on 2025-11-05 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrics', '0001_initial'),
        ('wearables', '0001_initial'),
        ('work_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='metric',
            name='wearable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='wearables.wearable', verbose_name='Wearable'),
        ),
        migrations.AddField(
            model_name='metric',
            name='work_session',
            field=models.ForeignKey(blank=True, help_text='Sesión de trabajo durante la cual se registró esta métrica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='work_sessions.worksession', verbose_name='Sesión de Trabajo'),
        ),
        migrations.AddField(
            model_name='metric',
            name='metric_type',
            field=models.ForeignKey(help_text='Tipo de métrica (heart_rate, steps, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='metrics.metrictype', verbose_name='Tipo de Métrica'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['user', 'metric_type', '-timestamp'], name='metrics_met_user_id_1be8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['work_session', '-timestamp'], name='metrics_met_work_se_3b6f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['wearable', '-timestamp'], name='metrics_met_wearabl_5a7759_idx'),
        ),
    ]
