# Generated by Django 5.1.3 on 2025-11-01 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrics', '0002_initial'),
        ('wearables', '0001_initial'),
        ('work_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='metric',
            name='wearable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='wearables.wearable', verbose_name='Wearable'),
        ),
        migrations.AddField(
            model_name='metric',
            name='work_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='work_sessions.worksession', verbose_name='Sesión de Trabajo'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['user', 'date'], name='metrics_met_user_id_12d9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['date'], name='metrics_met_date_b0617b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('user', 'date', 'timestamp')},
        ),
    ]
