# Generated by Django 5.1.3 on 2025-11-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, help_text='Token de Firebase Cloud Messaging para notificaciones push', null=True, verbose_name='FCM Token'),
        ),
    ]
