# Generated by Django 5.1.3 on 2025-11-01 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('category', models.CharField(choices=[('steps', 'Pasos'), ('heart_rate', 'Frecuencia Cardíaca'), ('recovery', 'Recuperación'), ('stress', 'Nivel de Estrés'), ('activity', 'Nivel de Actividad'), ('hrv', 'Variabilidad Cardíaca'), ('sleep', 'Horas de Sueño'), ('productivity', 'Productividad')], db_index=True, max_length=30, verbose_name='Categoría')),
                ('target', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Meta Objetivo')),
                ('current_progress', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Progreso Actual')),
                ('unit', models.CharField(help_text='Ej: pasos, bpm, horas, %', max_length=50, verbose_name='Unidad')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Finalización')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Completada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-created_at'],
            },
        ),
    ]
