# Generated by Django 5.1.3 on 2025-11-01 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'is_completed'], name='goals_goal_user_id_c14f76_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['category'], name='goals_goal_categor_07c7bc_idx'),
        ),
    ]
