# Generated by Django 5.1.3 on 2025-11-01 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Mañana'), ('afternoon', 'Tarde'), ('night', 'Noche'), ('custom', 'Personalizado')], db_index=True, max_length=20, verbose_name='Turno')),
                ('start_time', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Finalización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Sesión Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='departments.department', verbose_name='Departamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Trabajo',
                'verbose_name_plural': 'Sesiones de Trabajo',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_type', models.CharField(choices=[('break', 'Descanso'), ('meal', 'Comida'), ('rest', 'Pausa Corta')], max_length=20, verbose_name='Tipo de Intervalo')),
                ('start_time', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Finalización')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Duración (minutos)')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='work_sessions.worksession', verbose_name='Sesión de Trabajo')),
            ],
            options={
                'verbose_name': 'Intervalo de Descanso',
                'verbose_name_plural': 'Intervalos de Descanso',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['user', 'is_active'], name='work_sessio_user_id_957a49_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['start_time'], name='work_sessio_start_t_a3aa5a_idx'),
        ),
    ]
