# Generated by Django 5.1.3 on 2025-11-05 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wearable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Número de Serie')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('manufacturer', models.CharField(default='Generic', max_length=100, verbose_name='Fabricante')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('maintenance', 'Mantenimiento'), ('damaged', 'Dañado')], db_index=True, default='active', max_length=20, verbose_name='Estado')),
                ('firmware_version', models.CharField(blank=True, max_length=50, verbose_name='Versión de Firmware')),
                ('battery_level', models.IntegerField(blank=True, null=True, verbose_name='Nivel de Batería (%)')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Wearable',
                'verbose_name_plural': 'Wearables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WearableAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Asignación Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('wearable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='wearables.wearable', verbose_name='Wearable')),
            ],
            options={
                'verbose_name': 'Asignación de Wearable',
                'verbose_name_plural': 'Asignaciones de Wearables',
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='wearables_w_user_id_fa15f8_idx'), models.Index(fields=['wearable', 'is_active'], name='wearables_w_wearabl_1e38bf_idx')],
            },
        ),
    ]
