# Generated by Django 5.1.3 on 2025-11-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='Nombre de la Tarea')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], db_index=True, default='medium', max_length=20, verbose_name='Prioridad')),
                ('fatigue_risk_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], db_index=True, default='low', max_length=20, verbose_name='Nivel de Riesgo de Fatiga')),
                ('start_time', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Finalización')),
                ('estimated_duration', models.IntegerField(blank=True, null=True, verbose_name='Duración Estimada (minutos)')),
                ('actual_duration', models.IntegerField(blank=True, null=True, verbose_name='Duración Real (minutos)')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Completada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-start_time'],
            },
        ),
    ]
