# Generated by Django 5.1.3 on 2025-11-01 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('work_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='task',
            name='work_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='work_sessions.worksession', verbose_name='Sesión de Trabajo'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'is_completed'], name='tasks_task_user_id_1ae507_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['work_session', 'start_time'], name='tasks_task_work_se_741184_idx'),
        ),
    ]
