# Generated by Django 5.1.3 on 2025-11-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('individual', 'Reporte Individual'), ('department', 'Reporte de Departamento'), ('company', 'Reporte Corporativo'), ('fatigue', 'Análisis de Fatiga'), ('productivity', 'Análisis de Productividad')], db_index=True, max_length=30, verbose_name='Tipo de Reporte')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parámetros del Reporte')),
                ('content', models.JSONField(default=dict, verbose_name='Contenido del Reporte')),
                ('summary', models.TextField(blank=True, verbose_name='Resumen')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Generación')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='departments.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
    ]
