# Generated by Django 5.1.3 on 2025-11-01 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generado Por'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by', 'report_type'], name='reports_rep_generat_8a1579_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_29aaa5_idx'),
        ),
    ]
